# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 14:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tlsnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLSLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.CharField(max_length=20, verbose_name='Queue ID')),
                ('sender', models.CharField(max_length=55, verbose_name='Sender')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
