# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160228_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlslogentry',
            name='recipients',
            field=models.CharField(default='', max_length=255, verbose_name='Recipients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlslogentry',
            name='sender',
            field=models.CharField(max_length=255, verbose_name='Sender'),
        ),
    ]
