# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160228_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlslogentry',
            name='recipients',
            field=models.CharField(max_length=255, null=True, verbose_name='Recipients'),
        ),
    ]
