# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160228_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatoryTLSDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='Domain')),
            ],
        ),
    ]
